services:

  api:
    build: .
    ports:
    - "5000:5000"
    depends_on:
    - db

  db:
   image: mysql:8.0
   environment:
     MYSQL_DATABASE: almox
     MYSQL_ROOT_PASSWORD: "mysql_root"
   ports:
     - "3306:3306"
   volumes:
     - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql