services:

  api:
    image: flask-almox:1.0
    build: .
    ports:
    - "5000:5000"
    depends_on:
    - db

  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: almoxarifado
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./Almoxarifado.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
